apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: 
    app: my-app  
spec:
  containers:
  - name: nginx-container
    image: nginx
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx
        name: nginx-container

