apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
{{ include "helm-basic-example.commonLabels" . | indent 4 }}
spec:
  selector:
    app: nginx
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    name: http
