apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "kubeflow-test-01"
  region: "eu-central-1"
  version: "1.23" # This is the kubernetes version

availabilityZones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]

## https://eksctl.io/usage/cloudwatch-cluster-logging/#clusterconfig-examples
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager" , "scheduler"]

# eksctl scale nodegroup --cluster=kubeflow-test-01 --nodes=3 --name=ng-1-mng
managedNodeGroups:
  - name: ng-1-mng
    instanceType: t3.large
    minSize: 1
    maxSize: 6
    ssh: # use existing EC2 key
      publicKeyName: gerassimos-mitropoulos