apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx  
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx-test-autoscaler
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
